package com.signpost.snapshot;

import lombok.Getter;
import net.runelite.api.gameval.VarbitID;

/**
 * One constant per diary tier completion varbit ({@code VarbitID.<REGION>_DIARY_<TIER>_COMPLETE};
 * Karamja keeps its older {@code ATJUN_*_DONE} names for easy/medium/hard).
 */
@Getter
public enum DiaryTier
{
	ARDOUGNE_EASY(VarbitID.ARDOUGNE_DIARY_EASY_COMPLETE),
	ARDOUGNE_MEDIUM(VarbitID.ARDOUGNE_DIARY_MEDIUM_COMPLETE),
	ARDOUGNE_HARD(VarbitID.ARDOUGNE_DIARY_HARD_COMPLETE),
	ARDOUGNE_ELITE(VarbitID.ARDOUGNE_DIARY_ELITE_COMPLETE),
	DESERT_EASY(VarbitID.DESERT_DIARY_EASY_COMPLETE),
	DESERT_MEDIUM(VarbitID.DESERT_DIARY_MEDIUM_COMPLETE),
	DESERT_HARD(VarbitID.DESERT_DIARY_HARD_COMPLETE),
	DESERT_ELITE(VarbitID.DESERT_DIARY_ELITE_COMPLETE),
	FALADOR_EASY(VarbitID.FALADOR_DIARY_EASY_COMPLETE),
	FALADOR_MEDIUM(VarbitID.FALADOR_DIARY_MEDIUM_COMPLETE),
	FALADOR_HARD(VarbitID.FALADOR_DIARY_HARD_COMPLETE),
	FALADOR_ELITE(VarbitID.FALADOR_DIARY_ELITE_COMPLETE),
	FREMENNIK_EASY(VarbitID.FREMENNIK_DIARY_EASY_COMPLETE),
	FREMENNIK_MEDIUM(VarbitID.FREMENNIK_DIARY_MEDIUM_COMPLETE),
	FREMENNIK_HARD(VarbitID.FREMENNIK_DIARY_HARD_COMPLETE),
	FREMENNIK_ELITE(VarbitID.FREMENNIK_DIARY_ELITE_COMPLETE),
	KANDARIN_EASY(VarbitID.KANDARIN_DIARY_EASY_COMPLETE),
	KANDARIN_MEDIUM(VarbitID.KANDARIN_DIARY_MEDIUM_COMPLETE),
	KANDARIN_HARD(VarbitID.KANDARIN_DIARY_HARD_COMPLETE),
	KANDARIN_ELITE(VarbitID.KANDARIN_DIARY_ELITE_COMPLETE),
	KARAMJA_EASY(VarbitID.ATJUN_EASY_DONE),
	KARAMJA_MEDIUM(VarbitID.ATJUN_MED_DONE),
	KARAMJA_HARD(VarbitID.ATJUN_HARD_DONE),
	KARAMJA_ELITE(VarbitID.KARAMJA_DIARY_ELITE_COMPLETE),
	KOUREND_EASY(VarbitID.KOUREND_DIARY_EASY_COMPLETE),
	KOUREND_MEDIUM(VarbitID.KOUREND_DIARY_MEDIUM_COMPLETE),
	KOUREND_HARD(VarbitID.KOUREND_DIARY_HARD_COMPLETE),
	KOUREND_ELITE(VarbitID.KOUREND_DIARY_ELITE_COMPLETE),
	LUMBRIDGE_EASY(VarbitID.LUMBRIDGE_DIARY_EASY_COMPLETE),
	LUMBRIDGE_MEDIUM(VarbitID.LUMBRIDGE_DIARY_MEDIUM_COMPLETE),
	LUMBRIDGE_HARD(VarbitID.LUMBRIDGE_DIARY_HARD_COMPLETE),
	LUMBRIDGE_ELITE(VarbitID.LUMBRIDGE_DIARY_ELITE_COMPLETE),
	MORYTANIA_EASY(VarbitID.MORYTANIA_DIARY_EASY_COMPLETE),
	MORYTANIA_MEDIUM(VarbitID.MORYTANIA_DIARY_MEDIUM_COMPLETE),
	MORYTANIA_HARD(VarbitID.MORYTANIA_DIARY_HARD_COMPLETE),
	MORYTANIA_ELITE(VarbitID.MORYTANIA_DIARY_ELITE_COMPLETE),
	VARROCK_EASY(VarbitID.VARROCK_DIARY_EASY_COMPLETE),
	VARROCK_MEDIUM(VarbitID.VARROCK_DIARY_MEDIUM_COMPLETE),
	VARROCK_HARD(VarbitID.VARROCK_DIARY_HARD_COMPLETE),
	VARROCK_ELITE(VarbitID.VARROCK_DIARY_ELITE_COMPLETE),
	WESTERN_EASY(VarbitID.WESTERN_DIARY_EASY_COMPLETE),
	WESTERN_MEDIUM(VarbitID.WESTERN_DIARY_MEDIUM_COMPLETE),
	WESTERN_HARD(VarbitID.WESTERN_DIARY_HARD_COMPLETE),
	WESTERN_ELITE(VarbitID.WESTERN_DIARY_ELITE_COMPLETE),
	WILDERNESS_EASY(VarbitID.WILDERNESS_DIARY_EASY_COMPLETE),
	WILDERNESS_MEDIUM(VarbitID.WILDERNESS_DIARY_MEDIUM_COMPLETE),
	WILDERNESS_HARD(VarbitID.WILDERNESS_DIARY_HARD_COMPLETE),
	WILDERNESS_ELITE(VarbitID.WILDERNESS_DIARY_ELITE_COMPLETE);

	private final int varbitId;

	DiaryTier(int varbitId)
	{
		this.varbitId = varbitId;
	}
}
