package dev.reece.nta.snapshot;

import lombok.Getter;
import net.runelite.api.Varbits;

/**
 * One constant per {@code Varbits.DIARY_<AREA>_<TIER>} completion varbit.
 */
@Getter
public enum DiaryTier
{
	ARDOUGNE_EASY(Varbits.DIARY_ARDOUGNE_EASY),
	ARDOUGNE_MEDIUM(Varbits.DIARY_ARDOUGNE_MEDIUM),
	ARDOUGNE_HARD(Varbits.DIARY_ARDOUGNE_HARD),
	ARDOUGNE_ELITE(Varbits.DIARY_ARDOUGNE_ELITE),
	DESERT_EASY(Varbits.DIARY_DESERT_EASY),
	DESERT_MEDIUM(Varbits.DIARY_DESERT_MEDIUM),
	DESERT_HARD(Varbits.DIARY_DESERT_HARD),
	DESERT_ELITE(Varbits.DIARY_DESERT_ELITE),
	FALADOR_EASY(Varbits.DIARY_FALADOR_EASY),
	FALADOR_MEDIUM(Varbits.DIARY_FALADOR_MEDIUM),
	FALADOR_HARD(Varbits.DIARY_FALADOR_HARD),
	FALADOR_ELITE(Varbits.DIARY_FALADOR_ELITE),
	FREMENNIK_EASY(Varbits.DIARY_FREMENNIK_EASY),
	FREMENNIK_MEDIUM(Varbits.DIARY_FREMENNIK_MEDIUM),
	FREMENNIK_HARD(Varbits.DIARY_FREMENNIK_HARD),
	FREMENNIK_ELITE(Varbits.DIARY_FREMENNIK_ELITE),
	KANDARIN_EASY(Varbits.DIARY_KANDARIN_EASY),
	KANDARIN_MEDIUM(Varbits.DIARY_KANDARIN_MEDIUM),
	KANDARIN_HARD(Varbits.DIARY_KANDARIN_HARD),
	KANDARIN_ELITE(Varbits.DIARY_KANDARIN_ELITE),
	KARAMJA_EASY(Varbits.DIARY_KARAMJA_EASY),
	KARAMJA_MEDIUM(Varbits.DIARY_KARAMJA_MEDIUM),
	KARAMJA_HARD(Varbits.DIARY_KARAMJA_HARD),
	KARAMJA_ELITE(Varbits.DIARY_KARAMJA_ELITE),
	KOUREND_EASY(Varbits.DIARY_KOUREND_EASY),
	KOUREND_MEDIUM(Varbits.DIARY_KOUREND_MEDIUM),
	KOUREND_HARD(Varbits.DIARY_KOUREND_HARD),
	KOUREND_ELITE(Varbits.DIARY_KOUREND_ELITE),
	LUMBRIDGE_EASY(Varbits.DIARY_LUMBRIDGE_EASY),
	LUMBRIDGE_MEDIUM(Varbits.DIARY_LUMBRIDGE_MEDIUM),
	LUMBRIDGE_HARD(Varbits.DIARY_LUMBRIDGE_HARD),
	LUMBRIDGE_ELITE(Varbits.DIARY_LUMBRIDGE_ELITE),
	MORYTANIA_EASY(Varbits.DIARY_MORYTANIA_EASY),
	MORYTANIA_MEDIUM(Varbits.DIARY_MORYTANIA_MEDIUM),
	MORYTANIA_HARD(Varbits.DIARY_MORYTANIA_HARD),
	MORYTANIA_ELITE(Varbits.DIARY_MORYTANIA_ELITE),
	VARROCK_EASY(Varbits.DIARY_VARROCK_EASY),
	VARROCK_MEDIUM(Varbits.DIARY_VARROCK_MEDIUM),
	VARROCK_HARD(Varbits.DIARY_VARROCK_HARD),
	VARROCK_ELITE(Varbits.DIARY_VARROCK_ELITE),
	WESTERN_EASY(Varbits.DIARY_WESTERN_EASY),
	WESTERN_MEDIUM(Varbits.DIARY_WESTERN_MEDIUM),
	WESTERN_HARD(Varbits.DIARY_WESTERN_HARD),
	WESTERN_ELITE(Varbits.DIARY_WESTERN_ELITE),
	WILDERNESS_EASY(Varbits.DIARY_WILDERNESS_EASY),
	WILDERNESS_MEDIUM(Varbits.DIARY_WILDERNESS_MEDIUM),
	WILDERNESS_HARD(Varbits.DIARY_WILDERNESS_HARD),
	WILDERNESS_ELITE(Varbits.DIARY_WILDERNESS_ELITE);

	private final int varbitId;

	DiaryTier(int varbitId)
	{
		this.varbitId = varbitId;
	}
}
